### ISSUE TITLE
cmake install fails on missing modules/viscoelastic/veutils.h

### ISSUE THREAD

**Issue by oneZeroOneZeroOne** [epfl-ecps/channelflow#21]
Installation fails due to missing include file:

`.../channelflow/python-wrapper/cfwrapper.cpp:12:10: fatal error: modules/viscoelastic/veutils.h: No such file or directory`

This happens on a Debian system with the following cmake command:

`cmake $HOME/Desktop/channelflow2/channelflow/ -DCMAKE_BUILD_TYPE=debug -DCMAKE_INSTALL_PREFIX=$HOME/Desktop/channelflow2/channelflow/install/ -DCMAKE_CXX_COMPILER=/usr/bin/mpicxx -DWITH_PYTHON=ON -DUSE_MPI=OFF`

channelflow version: 2.0.2

The configuration summary is as follows:

```Compiler:                       GNU 8.3.0
   Build type:                     debug
   Install prefix:                 ~/Desktop/channelflow2/channelflow/install
   Building shared library:        yes
   Linking programs to:            shared library

   Libraries
   MPI:                            disabled
   netcdf (default file format):   enabled
   Parallel netcdf:                disabled
   HDF5 C++ (legacy file format):  disabled

   Channelflow components
   nsolver:                        enabled
   Python wrapper:                 enabled
   GTest unit testing:             enabled
```

quick FIX (for me):
comment out line #12 of 
`$HOME/Desktop/channelflow2/channelflow/python-wrapper/cfwrapper.cpp`
which reads
`#include "modules/viscoelastic/veutils.h"`
-> afterwards `make tests` passes 54/54

**Comment by mirkofarano** [comment]
> quick FIX (for me):
> comment out line #12 of
> $HOME/Desktop/channelflow2/channelflow/python-wrapper/cfwrapper.cpp
> which reads
> #include "modules/viscoelastic/veutils.h"

This is indeed the correct fix.
